---
shared:
  metrics_topk: &metrics_topk [20, 50, 100]

first_level:
  models:
    - model:
        type: src.first_level.models.ALS
        inner_model:
          type: implicit.cpu.als.AlternatingLeastSquares
          factors: 100
          num_threads: 4
          iterations: 100
        scaling:
          type: src.first_level.models.als.LinearScaling
          alpha: 40.0
        metrics_topk: *metrics_topk
      optuna:
        metric: ndcg@20
        study:
          n_trials: 5
          n_jobs: 1
        params:
          model.inner_model.factors:
            suggest: suggest_int
            low: 100
            high: 256
          model.inner_model.iterations:
            suggest: suggest_int
            low: 100
            high: 200
          model.scaling.alpha:
            suggest: suggest_float
            low: 30
            high: 50
    - model:
        type: src.first_level.models.MultVAE
        encoder:
          type: src.first_level.models.nn.FeedForward
          input_size: &input_size 300
          num_layers: 1
          hidden_sizes: [600]
          activations: tanh
        decoder:
          type: src.first_level.models.nn.FeedForward
          input_size: 200
          num_layers: 2
          hidden_sizes: [600, *input_size]
          activations: tanh
        kl_scheduler:
          type: src.first_level.models.multvae.KLScheduler
          zero_weight_steps: 200
          annealing_steps: 600
          max_weight: 0.2
        sample_size: 200
        metrics_topk: *metrics_topk
      train:
        engine:
          type: catalyst.dl.CPUEngine
        epochs: 30
        loader:
          batch_size: 128
          shuffle: true
          drop_last: true
        optimizer:
          _mode_: partial
          type: torch.optim.Adam
          lr: 0.001
        # callbacks:
        #   early_stopping:
        #     type: catalyst.dl.EarlyStoppingCallback
        #     loader_key: valid
        #     metric_key: ndcg20
        #     minimize: false
        #     patience: 30
        #     min_delta: 0.0001
    - model:
        type: src.first_level.models.EASE
        norm: True
        reg_weight: 100
        metrics_topk: *metrics_topk
      optuna:
        metric: ndcg@20
        study:
          n_trials: 5
          n_jobs: 1
        params:
          model.reg_weight:
            suggest: suggest_int
            low: 100
            high: 200
    - name: EASE-check
      model:
        type: src.first_level.models.EASE
        norm: True
        reg_weight: 100
        metrics_topk: *metrics_topk
      optuna:
        metric: ndcg@20
        study:
          n_trials: 5
          n_jobs: 1
        params:
          model.reg_weight:
            suggest: suggest_int
            low: 100
            high: 200
    - model:
        type: src.first_level.models.SLIM
        elastic_net:
          type: sklearn.linear_model.ElasticNet
          alpha: 1.0
          l1_ratio: 0.1
          positive: true
          fit_intercept: true
          copy_X: false
          precompute: True
          selection: random
          max_iter: 100
          tol: 0.0001
        metrics_topk: *metrics_topk
